from config.settings.base import *
DEBUG = False

ALLOWED_HOSTS = ['frontend',"backend"] 
CORS_ALLOWED_ORIGINS = [
    "https://example.com"
]
CORS_ALLOW_CREDENTIALS = True 
CORS_ALLOW_HEADERS = [
    'X-CSRFToken',
    'Content-Type',
    'Authorization',
]
SESSION_COOKIE_SAMESITE = 'Lax'
SESSION_COOKIE_SECURE = True
SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_NAME = 'sessionid'
SESSION_COOKIE_AGE = 86400 
SESSION_EXPIRE_AT_BROWSER_CLOSE = False 
SESSION_ENGINE = 'django.contrib.sessions.backends.db'
SESSION_SAVE_EVERY_REQUEST = False
SESSION_COOKIE_DOMAIN = ".example.com"

# Sécurité des cookies CSRF
CSRF_COOKIE_NAME = 'csrftoken'
CSRF_COOKIE_HTTPONLY = True
CSRF_COOKIE_SECURE = True
CSRF_COOKIE_SAMESITE = 'None'


HTTPONLY = True
SECURE = True  

X_FRAME_OPTIONS = 'DENY' 
SECURE_BROWSER_XSS_FILTER = True  
SECURE_CONTENT_TYPE_NOSNIFF = True 
SECURE_HSTS_SECONDS = 31536000
SECURE_SSL_REDIRECT = False
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
